Great_Homes_Realty/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from apps.LoginAndReg.models import User as U

class UAdmin(admin.ModelAdmin):
    pass
admin.site.register(U, UAdmin)


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include('apps.LoginAndReg.urls', namespace = "login")),
    url(r'^UserDashboard/', include('apps.UserDashboard.urls', namespace = "UserDashboard")),
    url(r'^', include('apps.GreatHomesRealty.urls', namespace = "GreatHomes"))    # url(r'^s3direct/', include('s3direct.urls'))
]

apps/GreatHomesRealty/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static 
from django.conf import settings
from . import views
from views import Suscribe, Unsuscribe, SendMail, ClientLogin, AddListing, EditListing

urlpatterns = [
	url(r'^$', views.index, name = "index"),
	url(r'^addListingDisplay$', views.addListingDisplay, name = "addListingDisplay"),
	url(r'^addListing$', AddListing.as_view(), name = "addListing"),
	url(r'^addListingImage/(?P<id>\d+)$', views.addListingImage, name = "addListingImage"),
	url(r'^addMainImage/(?P<id>\d+)$', views.addMainImage, name = "addMainImage"),
	url(r'^editListingDisplay/(?P<id>\d+)$', views.editListingDisplay, name = "editListingDisplay"),
	url(r'^editListing/(?P<id>\d+)$', EditListing.as_view(), name = "editListing"),
	url(r'^showListing/(?P<id>\d+)$', views.showListing, name = "showListing"),
	url(r'^showAllListing$', views.showAllListing, name = "showAllListing"),
	url(r'^showAllRentals$', views.showAllRentals, name = "showAllRentals"),
	url(r'^showAgentListing/(?P<id>\d+)$', views.showAgentListing, name = "showAgentListing"),
	url(r'^addAgent/(?P<id>\d+)$', views.addAgent, name = "addAgent"),
	url(r'^deleteListing/(?P<id>\d+)$', views.deleteListing, name = "deleteListing"),
	url(r'^deleteImage/(?P<id>\d+)$', views.deleteImage, name = "deleteImage"),
	url(r'^deleteListingAgent/(?P<id>\d+)$', views.deleteListingAgent, name = "deleteListingAgent"),
	url(r'^sendMail/(?P<id>\d+)$', SendMail.as_view(), name = "sendMail"),
	url(r'^deleteMainImage/(?P<id>\d+)$', views.deleteMainImage, name = "deleteMainImage"),
	url(r'^suscribeDisplay$', views.suscribeDisplay, name = "suscribeDisplay"),
	url(r'^suscribe$', Suscribe.as_view(), name = "suscribe"),
	url(r'^unsuscribe$', Unsuscribe.as_view(), name = "unsuscribe"),
	url(r'^clientLogin$', ClientLogin.as_view(), name = "clientLogin"),
	url(r'^suscriptionEmail$', views.suscriptionEmail, name = "suscriptionEmail"),
	url(r'^displaySubscribers$', views.displaySubscribers, name = "displaySubscribers"),
	url(r'^contact$', views.contact, name = "contact"),
	url(r'^buying$', views.buying, name = "buying"),
	url(r'^selling$', views.selling, name = "selling"),
	url(r'^mortgage$', views.mortgage, name = "mortgage"),
	url(r'^investing$', views.investing, name = "investing"),
	url(r'^owningHome$', views.owningHome, name = "owningHome"),
	url(r'^aboutUs$', views.aboutUs, name = "aboutUs"),
	url(r'^latLon$', views.latLon, name = "latLon")

]

apps/LoginAndReg/urls.py
from django.conf.urls import url, include 
from . import views
from views import Register, Login, ResetPassword, ChangePassword

urlpatterns = [
	url(r'^$', views.index, name = "index"),
	url(r'^users$', Register.as_view(), name = "register"),
	url(r'^login$', Login.as_view(), name = "login"),
	url(r'^updateInfo/(?P<id>\d+)$', views.updateInfo, name = "updateInfo"),
	url(r'^updatePassword/(?P<id>\d+)$', views.updatePassword, name = "updatePassword"),
	url(r'^updateDescription$', views.updateDescription, name = "updateDescription"),
	url(r'^removeUser/(?P<id>\d+)$', views.removeUser, name = "removeUser"),
	url(r'^createUser$', views.createUser, name = "createUser"),
	url(r'^resetPasswordDisplay$', views.resetPasswordDisplay, name = "resetPasswordDisplay"),
	url(r'^resetPassword$', ResetPassword.as_view(), name = "resetPassword"),
	url(r'^changePassword$', ChangePassword.as_view(), name = "changePassword")
	]

apps/UserDashboard/urls.py
from django.conf.urls import url, include # Notice we added include
from . import views
from views import PostMessage

urlpatterns = [
	url(r'^$', views.index, name = "index"),
	url(r'^users/new$', views.createDisplay, name = "createDisplay"),
	url(r'^users/edit$', views.editProfileDisplay, name = "editProfileDisplay"),
	url(r'^logout$', views.logout, name = "logout"),
	url(r'^users/edit/(?P<id>\d+)$', views.adminEdit, name = "adminEdit"),
	url(r'^postMessage$', PostMessage.as_view(), name = "postMessage"),
	url(r'^deleteMessage/(?P<id>\d+)$', views.deleteMessage, name = "deleteMessage"),
	url(r'^addUserImage/(?P<id>\d+)$', views.addUserImage, name = "addUserImage")
]

apps/UserDashboard/models.py
from __future__ import unicode_literals
from django.db import models
from ..LoginAndReg.models import User, LoginManager, RegisterManager
# Create your models here.

class Messages(models.Model):
	subject = models.TextField(null = True)
	message = models.TextField()
	user = models.ForeignKey(User, related_name = "poster")
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

class Comments(models.Model):
	comment = models.TextField()
	message = models.ForeignKey(Messages)
	user = models.ForeignKey(User)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

apps/UserDashboard/views.py
from django.shortcuts import render, HttpResponse, redirect
from models import Messages, Comments
from ..LoginAndReg.models import User, LoginManager, RegisterManager
from django.core.urlresolvers import reverse
from django.db.models import Count
from ..GreatHomesRealty.form import addListingForm, S3ImageForm
from django.views.generic.edit import CreateView
from boto.s3.connection import S3Connection
from boto.s3.key import Key
from django.conf import settings
import mimetypes
import random

def index(request):
	if request.session['login'] > 0:
		context = {
		    'users' : User.registerMgr.all(),
		    'activeUser': User.registerMgr.get(id = request.session['login']),
		    'user': User.registerMgr.get(id = request.session['login'])
		}
		return render(request, 'UserDashboard/index.html', context)
	else:
		return redirect(reverse('GreatHomes:index'))

def createDisplay(request):
	try:
		user = User.registerMgr.get(id = request.session['login'])
	except:
		user = "none"
	if user.user_level == "Admin":
		return render(request, 'UserDashBoard/newUser.html')
	else:
		return redirect(reverse('GreatHomes:index'))

def editProfileDisplay(request):
	if request.session['login'] > 0:
		user = User.registerMgr.get(id = request.session['login'])
		context = {
			'User': user
		}
		return render(request, 'UserDashboard/editProfile.html',  context )
	else:
		return redirect(reverse('GreatHomesRealty:index'))

def addUserImage(request, id):
	def store_in_s3(filename, content): 
		conn = S3Connection(settings.AWS_ACCESS_KEY_ID, settings.AWS_SECRET_ACCESS_KEY)
		b = conn.get_bucket('greathomesrealty')
		mime = mimetypes.guess_type(filename)[0]
		k = Key(b)
		k.key = filename
		k.set_metadata("Content-Type", mime)
		k.set_contents_from_string(content)
		# k.set_acl('public read')
	if request.session['login'] > 0 and request.method == "POST":
		user = User.registerMgr.get(id = id)
		if request.method == 'POST':
			form = S3ImageForm(request.POST, request.FILES)
			if form.is_valid():
				# user.picture = form.cleaned_data['picture']
				# user.save()
				file = request.FILES['file']
				filename = file.name
				specialNumber = random.randint(1,10000)
				specialName = str(specialNumber) + file.name
				content = file.read()
				store_in_s3(specialName, content)
				user.url = ('http://s3.amazonaws.com/greathomesrealty/' + specialName)
				user.save()
				url = "/showAgentListing/" + str(user.id)
				return redirect(url)
			else: 
				url = "/showAgentListing/" + str(user.id)
				return redirect(url)
	else:
		return redirect(reverse('GreatHomesRealty:index'))


	return
def adminEdit(request, id):
	try:
		user = User.registerMgr.get(id = request.session['login'])
	except:
		user = "none"
	if user.user_level == "Admin":
		admin = User.registerMgr.get(id = request.session['login'])
		user = User.registerMgr.get(id = id)
		context = {
			'User': user
		}
		return render(request, 'UserDashboard/adminEdit.html', context )
	else:
		return redirect(reverse('GreatHomes:index'))
		
def logout(request):
	request.session['login'] = 0
	request.session['reciever'] = 0
	return redirect(reverse('login:index'))

class PostMessage(CreateView):
	def get(self, request):
		try: 
			user = User.registerMgr.get(id = request.session['login'])
		except:
			user = "none"
		context = {
			'all_messages': Messages.objects.all(),
			'Admin': user
		}
		return render(request, 'GreatHomesRealty/newsfeedAjax.html', context)
	def post(self, request):
		newMessage = Messages.objects.create(message = request.POST['message'], subject = request.POST['subject'], user_id = request.session['login'] )
		return redirect(reverse('UserDashboard:postMessage'))
		
def deleteMessage(request, id):
		Messages.objects.get(id = id).delete()
		return redirect(reverse('GreatHomes:suscribeDisplay'))

apps/UserDashboard/templates/UserDashboard/adminEdit.html
<html>
    <head>
        <title>Admin Edit </title>
        {% load staticfiles %}
        <meta name="viewport" content="width=device-width, initial-scale=0.5">
        <script src = "{% static '/js/jquery.js' %}" type="text/javascript"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    </head>
    <style>
    {% load staticfiles %}
    .error {
      color:red;
      margin-left: 200px;
    }
    .green {
      color: green;
    }
    .btn {
      margin-top: 15px;
    }
    h1 {
      margin-left: 50px;
    }
    ul {
      list-style-type: none;
      display: inline-block;
      width: 70%;
    }
    li {
      display: inline-block;
      margin-left: 5%;
      margin-top: 1.5%;
      font-size: 1.5em;
    }
    a {
      color: rgb(55, 150, 239);
    }
    .Manage {
      display: inline-block;
    }
</style>
    <body>
  {% if request.session.login > 0 %}
  <header>
    <ul>
      <li><a href="{%url 'GreatHomes:index' %}">HomePage</a></li>
      <li><a href="{%url 'UserDashboard:index' %}">DashBoard</a></li>
      <li><a href="{%url 'UserDashboard:editProfileDisplay' %}">Edit Profile</a></li>
      <li><a href="{%url 'GreatHomes:showAgentListing' id=request.session.login %}">Your Profile</a></li>
      <li><a href="{%url 'GreatHomes:showAllListing' %}">Listings</a></li>
      <li><a href="{%url 'GreatHomes:addListingDisplay' %}">Add Listing</a></li>
    {% if user.user_level == "Admin" %}
      <li><a href="{%url 'UserDashboard:createDisplay' %}">Add New Agent</a></li>
    {% endif %}
      <li><a href="{%url 'UserDashboard:logout' %}">Log Off</a></li>
    </ul>
  </header>
  {% endif %}

  <div class = "container">
      <form action="{%url 'login:updateInfo' id=User.id %}" method='post' class = "form-horizontal">
        {% csrf_token %}
          <h1> Edit {{User.firstName}}'s Information</h1>
          {% if error_messages.TwoCharacters %}
            <p class = 'error'> {{ error_messages.TwoCharacters }} </p>
          {% endif %}
          {% if error_messages.IsAlpha %}
            <p class = 'error'> {{ error_messages.IsAlpha }} </p>
          {% endif %}
          <div class = "form-group">
            <label for ="first_name" class="col-sm-3 control-label">First Name:</label>
            <div class = "col-sm-8">
              <input type='text' class = "form-control" name='first_name' id = "first_name" value = "{{User.firstName}}" "First Name"> 
            </div>
          </div>
          <div class = "form-group">
            <label for = "last_name" class = "col-sm-3 control-label">Last Name:</label>
            <div class = "col-sm-8">
              <input type='text' name='last_name' class = "form-control" id = "last_name" value = "{{User.lastName}}">
            </div>
          </div>
          {% if error_messages.EmailRequired %}
            <p class = 'error'> {{ error_messages.EmailRequired }} </p>
          {% endif %}
          {% if error_messages.InvalidEmail %}
            <p class = 'error'> {{ error_messages.InvalidEmail }} </p>
          {% endif %}
          {% if error_messages.EmailDuplicate %}
            <p class = 'error'> {{ error_messages.EmailDuplicate }} </p>
          {% endif %}
        <div class = "form-group">
          <label for = "email" class = "col-sm-3 control-label">Email:</label>
          <div class = "col-sm-8">
            <input type='text' name='email' class = "form-control" id = "email" value = "{{User.email}}">
          </div>
        </div>
        {% if error_messages.InvalidPhone %}
            <p class = 'error'> {{ error_messages.InvalidPhone }} </p>
        {% endif %}
        <div class = "form-group">
          <label for = "phone" class = "col-sm-3 control-label">Phone Number: (XXX)-XXX-XXXX </label>
          <div class = "col-sm-8">
            <input type='text' name='phone' class = "form-control" id = "phone" value = "{{User.phone}}">
            <input type='submit' value='Save' class = "btn btn-warning">
          </div>
        </div>
      </form>

     <form action="{%url 'login:updatePassword' id=User.id%}" method='post' class = "form-horizontal">
      {% csrf_token %}
         {% if error_messages.PasswordRequired %}
            <p class = 'error'> {{ error_messages.PasswordRequired }} </p>
          {% endif %}
          {% if error_messages.PasswordLength %}
            <p class = 'error'> {{ error_messages.PasswordLength }} </p>
          {% endif %}
          {% if error_messages.InvalidPassword %}
            <p class = 'error'> {{ error_messages.InvalidPassword }} </p>
          {% endif %}
          {% if error_messages.PasswordNonmatch %}
            <p class = 'error'> {{ error_messages.PasswordNonmatch }} </p>
          {% endif %}
        <div class = "form-group">
          <label for = "password" class = "col-sm-3 control-label">Password:</label>
          <div class = "col-sm-8">
            <input type='password' name='password' class = "form-control" id = "password" placeholder = "Password">
          </div>
        </div>
        <div class = "form-group">
          <label for = "confirmpassword" class = "col-sm-3 control-label">Confirm Password:</label>
          <div class = "col-sm-8">
            <input type='password' name='confirm_password' class = "form-control" id = "confirmpassword"placeholder = "Password">
            <input type='submit' value='Update Password' class = "btn btn-warning">
          </div>
        </div>
        </form>
    </div>
    </body>
</html>

apps/UserDashboard/templates/UserDashboard/editProfile.html
<html>
    <head>
        <title>Login and Reg Index</title>
        {% load staticfiles %}
         <meta name="viewport" content="width=device-width, initial-scale=0.5">
         <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    </head>
    <style>
    {% load staticfiles %}
    .error {
      color:red;
      margin-left: 200px;
    }
    .green {
      color: green;
    }
    .btn {
      margin-top: 15px;
    }
    h1 {
      margin-left: 50px;
    }
    ul {
      list-style-type: none;
      display: inline-block;
      width: 70%;
    }
    li {
      display: inline-block;
      margin-left: 5%;
      margin-top: 1.5%;
      font-size: 1.5em;
    }
    a {
      color: rgb(55, 150, 239);
    }
    .Manage {
      display: inline-block;
    }
    .addPicture {
      font-size: 1.5em;
      margin-top: 25%;
    }
</style>
    <body>
  {% if request.session.login > 0 %}
  <header>
    <ul>
      <li><a href="{%url 'GreatHomes:index' %}">HomePage</a></li>
      <li><a href="{%url 'UserDashboard:index' %}">DashBoard</a></li>
      <li><a href="{%url 'UserDashboard:editProfileDisplay' %}">Edit Profile</a></li>
      <li><a href="{%url 'GreatHomes:showAgentListing' id=request.session.login %}">Your Profile</a></li>
      <li><a href="{%url 'GreatHomes:showAllListing' %}">Listings</a></li>
      <li><a href="{%url 'GreatHomes:addListingDisplay' %}">Add Listing</a></li>
    {% if user.user_level == "Admin" %}
      <li><a href="{%url 'UserDashboard:createDisplay' %}">Add New Agent</a></li>
    {% endif %}
      <li><a href="{%url 'UserDashboard:logout' %}">Log Off</a></li>
    </ul>
  </header>
  {% endif %}

  <div class = "container">
    <div class = "row">
      <div class = "col-md-10">
      <form action="{%url 'login:updateInfo' id=0 %}" method='post' class = "form-horizontal">
        {% csrf_token %}
          <h1>Edit Your Profile</h1>
          {% if error_messages.TwoCharacters %}
            <p class = 'error'> {{ error_messages.TwoCharacters }} </p>
          {% endif %}
          {% if error_messages.IsAlpha %}
            <p class = 'error'> {{ error_messages.IsAlpha }} </p>
          {% endif %}
          <div class = "form-group">
            <label for ="first_name" class="col-sm-3 control-label">First Name:</label>
            <div class = "col-sm-9">
              <input type='text' class = "form-control" name='first_name' id = "first_name" value = "{{User.firstName}}"> 
            </div>
          </div>
          <div class = "form-group">
            <label for = "last_name" class = "col-sm-3 control-label">Last Name:</label>
            <div class = "col-sm-9">
              <input type='text' name='last_name' class = "form-control" id = "last_name" value = "{{User.lastName}}">
            </div>
          </div>
          {% if error_messages.EmailRequired %}
            <p class = 'error'> {{ error_messages.EmailRequired }} </p>
          {% endif %}
          {% if error_messages.InvalidEmail %}
            <p class = 'error'> {{ error_messages.InvalidEmail }} </p>
          {% endif %}
          {% if error_messages.EmailDuplicate %}
            <p class = 'error'> {{ error_messages.EmailDuplicate }} </p>
          {% endif %}
        <div class = "form-group">
          <label for = "email" class = "col-sm-3 control-label">Email:</label>
          <div class = "col-sm-9">
            <input type='text' name='email' class = "form-control" id = "email" value = "{{User.email}}">
          </div>
        </div>
        {% if error_messages.InvalidPhone %}
            <p class = 'error'> {{ error_messages.InvalidPhone }} </p>
        {% endif %}
        <div class = "form-group">
          <label for = "phone" class = "col-sm-3 control-label">Phone Number: (XXX)-XXX-XXXX </label>
          <div class = "col-sm-9">
            <input type='tel' name='phone' class = "form-control" id = "phone" value = "{{User.phone}}">
           <input type='submit' value='Save' class = "btn btn-warning">
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

  <div class = "container">
    <div class = "row">
      <div class = "col-md-10">
     <form action="{%url 'login:updatePassword' id=0%}" method='post' class = "form-horizontal">
      {% csrf_token %}
         {% if PasswordRequired %}
            <p class = 'error'> {{ PasswordRequired }} </p>
          {% endif %}
          {% if PasswordLength %}
            <p class = 'error'> {{ PasswordLength }} </p>
          {% endif %}
          {% if InvalidPassword %}
            <p class = 'error'> {{ InvalidPassword }} </p>
          {% endif %}
          {% if PasswordNonmatch %}
            <p class = 'error'> {{ PasswordNonmatch }} </p>
          {% endif %}
        <div class = "form-group">
          <label for = "password" class = "col-sm-3 control-label">Password:</label>
          <div class = "col-sm-9">
            <input type='password' name='password' class = "form-control" id = "password" placeholder = "Password">
          </div>
        </div>
        <div class = "form-group">
          <label for = "confirmpassword" class = "col-sm-3 control-label">Confirm Password:</label>
          <div class = "col-sm-9">
            <input type='password' name='confirm_password' class = "form-control" id = "confirmpassword"placeholder = "Password">
            <input type='submit' value='Update Password' class = "btn btn-warning">
          </div>
        </div>
        </form>
        </div>
      </div>
    </div>

  <div class = "container">
    <div class = "row">
      <div class = "col-md-10">
       <form action="{%url 'login:updateDescription' %}" method='post' class = "form-horizontal">
        {% csrf_token %}
          <div class="form-group">
            <label for="description" class = "col-sm-3 control-label">Edit Description:</label>
            <div class = "col-sm-9">
            <textarea class="form-control" rows="5" name="description" id="description" value = "{{User.profileInformation}}"></textarea>
            <p>{{User.profileInformation}}</p>
            <input type='submit' value='Edit Description' class = "btn btn-warning">
           </div>
         </div>
       </form>
        </div>
      </div>
    </div> 
    </body>
</html>

apps/UserDashboard/templates/UserDashboard/index.html
<html>
<head>
	<title>User_Dashboard</title>
	{% load staticfiles %}
	 <meta name="viewport" content="width=device-width, initial-scale=0.5">
	<script src = "{% static '/js/jquery.js' %}" type="text/javascript"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<style>
	{% load staticfiles %}
	.Manage {
		display: inline-block;
	}
	a {
		color: rgb(55, 150, 239);
	}
	#removeUser {
		display: inline-block;
		margin-left: 2%;
	}
</style>
<body>
	{% if request.session.login > 0 %}
	<header>
		<ul>
			<li><a href="{%url 'GreatHomes:index' %}">HomePage</a></li>
			<li><a href="{%url 'UserDashboard:index' %}">DashBoard</a></li>
			<li><a href="{%url 'UserDashboard:editProfileDisplay' %}">Edit Profile</a></li>
			<li><a href="{%url 'GreatHomes:showAgentListing' id=request.session.login %}">Your Profile</a></li>
			<li><a href="{%url 'GreatHomes:showAllListing' %}">Listings</a></li>
			<li><a href="{%url 'GreatHomes:addListingDisplay' %}">Add Listing</a></li>
		{% if user.user_level == "Admin" %}
			<li><a href="{%url 'UserDashboard:createDisplay' %}">Add New Agent</a></li>
		{% endif %}
			<li><a href="{%url 'UserDashboard:logout' %}">Log Off</a></li>
		</ul>
	</header>
	{% endif %}

	<div class = "col-sm-4">
		<h2 class = "Manage">Company Agents</h2>
	</div>

	<div class = "table-responsive col-sm-12">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Name</th>
				<th>Email</th>
				<th>Phone #</th>
				<th>Joined Date</th>
				{% if user.user_level == "Admin" %}
				<th>Actions</th>
				{% endif %}
			</tr>	
		</thead>
		<tbody>
			{% for user in users %}
			<tr>
				<td><a href="{%url 'GreatHomes:showAgentListing' id=user.id %}">{{user.firstName}} {{user.lastName}}</a></td>
				<td>{{user.email}}</td>
				<td>{{user.phone}}</td>
				<td>{{user.created_at}}</td>
			{% if activeUser.user_level == "Admin" %}
				<td class = "td-buttons"><a class = "btn btn-success" href="{%url 'UserDashboard:adminEdit' id=user.id %}">Edit</a><form id="removeUser" action = "{%url 'login:removeUser' id=user.id %}">
				{% csrf_token %}
				 <button class = "btn btn-danger"
				 onclick="return myFunction()">Remove</button>
				</form></td>
			{% endif %}
			</tr>
			{% endfor %}
		</tbody>
	</table>
	</div>
</body>
<script type="text/javascript">
	function myFunction() {
	    if (confirm("Are you sure you want to remove user? ") == true) {
	    	document.getElementById('removeUser').submit();
		    }
	    else {
        	return false;
        	alert("nope");
	  	}
	}
</script>
</html>