Great_Homes_Realty/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from apps.LoginAndReg.models import User as U

class UAdmin(admin.ModelAdmin):
    pass
admin.site.register(U, UAdmin)


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include('apps.LoginAndReg.urls', namespace = "login")),
    url(r'^UserDashboard/', include('apps.UserDashboard.urls', namespace = "UserDashboard")),
    url(r'^', include('apps.GreatHomesRealty.urls', namespace = "GreatHomes"))    # url(r'^s3direct/', include('s3direct.urls'))
]

apps/GreatHomesRealty/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static 
from django.conf import settings
from . import views
from views import Suscribe, Unsuscribe, SendMail, ClientLogin, AddListing, EditListing

urlpatterns = [
	url(r'^$', views.index, name = "index"),
	url(r'^addListingDisplay$', views.addListingDisplay, name = "addListingDisplay"),
	url(r'^addListing$', AddListing.as_view(), name = "addListing"),
	url(r'^addListingImage/(?P<id>\d+)$', views.addListingImage, name = "addListingImage"),
	url(r'^addMainImage/(?P<id>\d+)$', views.addMainImage, name = "addMainImage"),
	url(r'^editListingDisplay/(?P<id>\d+)$', views.editListingDisplay, name = "editListingDisplay"),
	url(r'^editListing/(?P<id>\d+)$', EditListing.as_view(), name = "editListing"),
	url(r'^showListing/(?P<id>\d+)$', views.showListing, name = "showListing"),
	url(r'^showAllListing$', views.showAllListing, name = "showAllListing"),
	url(r'^showAllRentals$', views.showAllRentals, name = "showAllRentals"),
	url(r'^showAgentListing/(?P<id>\d+)$', views.showAgentListing, name = "showAgentListing"),
	url(r'^addAgent/(?P<id>\d+)$', views.addAgent, name = "addAgent"),
	url(r'^deleteListing/(?P<id>\d+)$', views.deleteListing, name = "deleteListing"),
	url(r'^deleteImage/(?P<id>\d+)$', views.deleteImage, name = "deleteImage"),
	url(r'^deleteListingAgent/(?P<id>\d+)$', views.deleteListingAgent, name = "deleteListingAgent"),
	url(r'^sendMail/(?P<id>\d+)$', SendMail.as_view(), name = "sendMail"),
	url(r'^deleteMainImage/(?P<id>\d+)$', views.deleteMainImage, name = "deleteMainImage"),
	url(r'^suscribeDisplay$', views.suscribeDisplay, name = "suscribeDisplay"),
	url(r'^suscribe$', Suscribe.as_view(), name = "suscribe"),
	url(r'^unsuscribe$', Unsuscribe.as_view(), name = "unsuscribe"),
	url(r'^clientLogin$', ClientLogin.as_view(), name = "clientLogin"),
	url(r'^suscriptionEmail$', views.suscriptionEmail, name = "suscriptionEmail"),
	url(r'^displaySubscribers$', views.displaySubscribers, name = "displaySubscribers"),
	url(r'^contact$', views.contact, name = "contact"),
	url(r'^buying$', views.buying, name = "buying"),
	url(r'^selling$', views.selling, name = "selling"),
	url(r'^mortgage$', views.mortgage, name = "mortgage"),
	url(r'^investing$', views.investing, name = "investing"),
	url(r'^owningHome$', views.owningHome, name = "owningHome"),
	url(r'^aboutUs$', views.aboutUs, name = "aboutUs"),
	url(r'^latLon$', views.latLon, name = "latLon")

]

apps/UserDashboard/urls.py
from django.conf.urls import url, include # Notice we added include
from . import views
from views import PostMessage

urlpatterns = [
	url(r'^$', views.index, name = "index"),
	url(r'^users/new$', views.createDisplay, name = "createDisplay"),
	url(r'^users/edit$', views.editProfileDisplay, name = "editProfileDisplay"),
	url(r'^logout$', views.logout, name = "logout"),
	url(r'^users/edit/(?P<id>\d+)$', views.adminEdit, name = "adminEdit"),
	url(r'^postMessage$', PostMessage.as_view(), name = "postMessage"),
	url(r'^deleteMessage/(?P<id>\d+)$', views.deleteMessage, name = "deleteMessage"),
	url(r'^addUserImage/(?P<id>\d+)$', views.addUserImage, name = "addUserImage")
]

apps/GreatHomesRealty/views.py
from django.shortcuts import render, HttpResponse, redirect
from ..LoginAndReg.models import User, LoginManager, RegisterManager
from ..UserDashboard.models import Messages
from .form import addListingForm, S3ImageForm
from models import Listing, User_Listings, Image, ListingManager, Client
from django.core.urlresolvers import reverse
try:
    from django.db.models.fields.related_descriptors import ReverseManyToOneDescriptor as ReverseDescriptor
except ImportError:
    from django.db.models.fields.related import ReverseManyRelatedObjectsDescriptor as ReverseDescriptor
from django.core.mail import send_mail, send_mass_mail
from django.conf import settings
import json 
from django.http import JsonResponse
from django.views.generic.edit import View
from django.views.generic import FormView
from boto.s3.connection import S3Connection
from boto.s3.key import Key
from django.conf import settings
import mimetypes
import random 
from django.db.models import Q
error_messages = {}


def index(request):
	allListings = Listing.listingMgr.filter(price__gte = 300000).filter(price__lte = 700000).order_by('-created_at')[0:6]
	try:
		user = User.registerMgr.get(id = request.session['login'])
	except:
		user = 0
	context = {
		'allListings': allListings,
		'user':user,
	}
	return render(request, 'GreatHomesRealty/index.html', context)

def addListingDisplay(request):
	if request.session['login']:
		addListing = addListingForm()
		context = {
			'addListing': addListing,
		}
		return render(request, 'GreatHomesRealty/addListing.html', context)
	else:
		return redirect(reverse('GreatHomes:index'))

class AddListing(View):
	def post(self, request):
		if request.method == "POST":
			error_messages = {}
			result = Listing.listingMgr.addListing(request.POST['streetAddress'], request.POST['suite'], request.POST['city'], request.POST['state'], request.POST['zipcode'], request.POST['price'], request.POST['bedrooms'], request.POST['bathrooms'], request.POST['squarefootage'], request.POST['housetype'], request.POST['county'], request.POST['neighborhood'], request.POST['mls'], request.POST['description'], "no", request.session['login'], request.POST['yearBuilt'], request.POST['status'])
			if result[0]:
				global listing
				error_messages['listing'] = result[1]
				return JsonResponse({"data": result[1]})
			else:
				error_messages = result[1]
				return JsonResponse(error_messages)
		else: 
			return JsonResponse({"error": "false"})

def editListingDisplay(request, id):
	if request.session['login']:
		listing = Listing.listingMgr.get(id = id)
		context = {
			'listing': listing
			# 'editForm': editForm
		}
		return render(request, 'GreatHomesRealty/editListing.html', context)
	else:
		return redirect(reverse('GreatHomes:index'))

class EditListing(View):
	def post(self, request, id):
		marker = False 
		user_listings = User_Listings.objects.filter(listing_id = id)
		currentUser = User.registerMgr.get(id = request.session['login'])
		for item in user_listings:
			if currentUser == item.user:
				marker = True
		if request.method == "POST" and (currentUser.user_level == "Admin" or marker == True):
			error_messages = {}
			listingone = Listing.listingMgr.get(id = id)
			result = Listing.listingMgr.addListing(request.POST['streetAddress'], request.POST['suite'], request.POST['city'], request.POST['state'], request.POST['zipcode'], request.POST['price'], request.POST['bedrooms'], request.POST['bathrooms'], request.POST['squarefootage'], request.POST['housetype'], request.POST['county'], request.POST['neighborhood'], request.POST['mls'], request.POST['description'], listingone.id, listingone.createdById, request.POST['yearBuilt'], request.POST['status'])
			if result[0]:
				print result[1]
				return JsonResponse({"data": result[1]})
			else:
				error_messages = result[1]
				return JsonResponse(error_messages)
		else:
			return JsonResponse({"error": "false"})

def addMainImage(request, id):
	def store_in_s3(filename, content): 
		conn = S3Connection(settings.AWS_ACCESS_KEY_ID, settings.AWS_SECRET_ACCESS_KEY)
		b = conn.get_bucket('greathomesrealty')
		mime = mimetypes.guess_type(filename)[0]
		k = Key(b)
		k.key = filename
		k.set_metadata("Content-Type", mime)
		k.set_contents_from_string(content)
	listing = Listing.listingMgr.get(id = id)
	if request.method == 'POST':
		form = S3ImageForm(request.POST, request.FILES)
		if form.is_valid():
			file = request.FILES['file']
			filename = file.name
			specialNumber = random.randint(1,10000)
			specialName = str(specialNumber) + file.name
			content = file.read()
			store_in_s3(specialName, content)
			listing.url = ('http://s3.amazonaws.com/greathomesrealty/' + specialName)
			listing.save()
			url = "/showListing/" + str(listing.id)
			return redirect(url)
		else: 
			url = "/showListing/" + str(listing.id)
			return redirect(url)
	else:
		url = "/showListing/" + str(listing.id)
		return redirect(url)

def addListingImage(request, id):
	def store_in_s3(filename, content): 
		conn = S3Connection(settings.AWS_ACCESS_KEY_ID, settings.AWS_SECRET_ACCESS_KEY)
		b = conn.get_bucket('greathomesrealty')
		mime = mimetypes.guess_type(filename)[0]
		k = Key(b)
		k.key = filename
		k.set_metadata("Content-Type", mime)
		k.set_contents_from_string(content)
	if request.method == "POST":
		listing = Listing.listingMgr.get(id = id)
		form = S3ImageForm(request.POST, request.FILES)
		if form.is_valid():
			for item in request.FILES.getlist('file'):
				file = item
				filename = file.name
				specialNumber = random.randint(1,10000)
				specialName = str(specialNumber) + file.name
				content = file.read()
				store_in_s3(specialName, content)
				addImage = Image.objects.create(listing_id = listing.id)
				addImage.url = ('http://s3.amazonaws.com/greathomesrealty/' + specialName)
				addImage.save()
			url = "/showListing/" + str(listing.id)
			return redirect(url)
		else:
			url = "/showListing/" + str(listing.id)
			return redirect(url)
	else: 
		url = "/showListing/" + str(id)
		return redirect(url)

def showListing(request, id):
	listing = Listing.listingMgr.get(id = id)
	addImage = S3ImageForm()
	try:
		currentUser = User.registerMgr.get(id = request.session['login'])
	except:
		currentUser = 0
	mainImage = S3ImageForm()
	listingAddress = listing.addressStreet + " " +listing.addressCity + " " + listing.addressState
	context = {
		'listing': listing,
		'addImage': addImage,
		'mainImage': mainImage,
		'images': Image.objects.filter(listing_id = listing.id),
		'agents': User.registerMgr.all(),
		'primaryAgents': User_Listings.objects.filter(listing_id = id),
		'listingAddress':listingAddress,
		'currentUser': currentUser,
		'counter': 0
	}
	return render(request, 'GreatHomesRealty/showListing.html',  context )

def addAgent(request, id):
	if request.method == "POST":
		agent = User(id = request.POST['agent'])
		listing = Listing.listingMgr.get(id = id)
		notnew = User_Listings.objects.filter(user_id = agent.id, listing_id = listing.id)
		if notnew:
			pass
		else:
			User_Listings.objects.create(user_id = agent.id, listing_id = listing.id)
		url = "/showListing/" + str(listing.id)
		return redirect(url)
	else: 
		url = "/showListing/" + str(id)
		return redirect(url)

def showAllListing(request):
	allListings = Listing.listingMgr.all().exclude(status = "For Rent").exclude(status = "Rented Out").order_by('price')
	context = {
		'allListings': allListings
	}
	return render(request, 'GreatHomesRealty/viewAllListing.html',  context )

def showAllRentals(request):
	allListings = Listing.listingMgr.filter(Q(status = "Rented Out") | Q(status = "For Rent")).order_by('price')
	context = {
		'allListings': allListings
	}
	return render(request, 'GreatHomesRealty/allRentals.html',  context )

def showAgentListing(request, id):
	user = User.registerMgr.get(id = id)
	listing = User_Listings.objects.filter(user = user)
	context = {
		'listings': listing,
		'user':user,
		'UserImage': S3ImageForm()
	}
	return render(request, 'GreatHomesRealty/agentListings.html',  context )

def deleteListing(request, id):
	if request.method == "POST":
		listing = Listing.listingMgr.get(id = id)
		userListing = User_Listings.objects.filter(listing = listing).delete()
		listing.delete()
		return redirect(reverse('GreatHomes:showAllListing'))
	else:
		return redirect(reverse('GreatHomes:showAllListing'))

def deleteImage(request, id):
	listing = Listing.listingMgr.get(images__id = id)
	image = Image.objects.get(id = id)
	image.delete()
	url = "/showListing/" + str(listing.id)
	return redirect(url)

def deleteMainImage(request, id):
	listing = Listing.listingMgr.get(id = id)
	listing.url = ""
	listing.save()
	url = "/showListing/" + str(listing.id)
	return redirect(url)

def deleteListingAgent(request, id):
	if request.method == "POST":
		agent = User(id = request.POST['agent'])
		listing = Listing.listingMgr.get(id = id)
		User_Listings.objects.filter(user_id = agent.id, listing_id = listing.id).delete()
		url = "/showListing/" + str(listing.id)
		return redirect(url)
	else:
		url = "/showListing/" + str(id)
		return redirect(url)

class SendMail(View):
	def post(self, request, id):
		if request.method == "POST":
			emails = []
			sendMailMessages = {}
			if id == "0":
				pass
			else:
				listing = Listing.listingMgr.get(id = id)
				manyToMany = User_Listings.objects.filter(listing_id = id)
				for item in manyToMany:
					emails.append(item.user.email)
			emails.append("billyu99@gmail.com")
			emails.append("John123Yu@gmail.com")
			results = Client.sendMailMgr.sendMail(request.POST['first_name'], request.POST['last_name'],request.POST['phone'], request.POST['email'], request.POST['message'])
			if results[0]:
				sendMailMessages['success'] = "Your email has been sent. An agent will get back to you shortly."
				fromEmail = request.POST['email']
				subject = request.POST['first_name'] + " " + request.POST['last_name'] + " " + "Prospective Client"
				if id == "0":

apps/GreatHomesRealty/templates/GreatHomesRealty/agentListings.html
<html>
<head>
	<title></title>
	{% load staticfiles %}
	 <meta name="viewport" content="width=device-width, initial-scale=0.5">
	<script src = "{% static '/js/jquery.js' %}" type="text/javascript"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'GreatHomesRealty/ionicons.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<style>	
	i {
		font-size: 1.5em;
		position: relative;
		top: .15em;
	}
	h2 {
		font-weight: 700;
	}
	.main {
		margin-top: 4%;
	}
	.main2 {
		background: linear-gradient(rgba(250, 197, 100, .95), rgba(250, 197, 100, .95));
		border-radius: 5%;
		padding: 2%;
		padding-left: 3%;
	}
	.userPicture {
		margin-top: 5%;
		border: 1.5px solid lightgrey;
		border-radius: 5%;
	}
	.profileinfo {
		margin-top: 3%;
	}
	p a {
		color: black;
	}
	p a:hover {
		color: darkblue;
	}
	.listings {
		background: linear-gradient(rgba(250, 197, 100, .95), rgba(250, 197, 100, .95));
		border-radius: 5%;
		padding-left: 3%;
		padding-bottom: 3%;
		min-height: 100px;
	}
</style>
<body>
	{% if request.session.login > 0 %}
	<header>
		<ul>
			<li><a href="{%url 'GreatHomes:index' %}">HomePage</a></li>
			<li><a href="{%url 'UserDashboard:index' %}">DashBoard</a></li>
			<li><a href="{%url 'UserDashboard:editProfileDisplay' %}">Edit Profile</a></li>
			<li><a href="{%url 'GreatHomes:showAgentListing' id=request.session.login %}">Your Profile</a></li>
			<li><a href="{%url 'GreatHomes:showAllListing' %}">Listings</a></li>
			<li><a href="{%url 'GreatHomes:addListingDisplay' %}">Add Listing</a></li>
		{% if user.user_level == "Admin" %}
			<li><a href="{%url 'UserDashboard:createDisplay' %}">Add New Agent</a></li>
		{% endif %}
			<li><a href="{%url 'UserDashboard:logout' %}">Log Off</a></li>
		</ul>
	</header>
	{% endif %}
	<div class = "header">
		<div class = "container-fluid">
			<div class = "col-sm-5">
				<h1><a href="{%url 'GreatHomes:index' %}"><i class = "ion-ios-home"></i> Great Homes Realty</a></h1>
			</div>
			<div class = "col-sm-7 navlinks">
				<ul>
					<li>
						  <a class="dropdown-toggle" data-toggle="dropdown">All Listings
						  <span class="caret"></span></a>
						  <ul class="dropdown-menu">
						    <li><a href="{%url 'GreatHomes:showAllListing' %}">For Sale</a></li>
						    <li><a href="{%url 'GreatHomes:showAllRentals' %}">For Rent</a></li>
						  </ul>
					</li>
					<li>
						  <a class="dropdown-toggle" data-toggle="dropdown">Buying
						  <span class="caret"></span></a>
						  <ul class="dropdown-menu">
						    <li><a href="{%url 'GreatHomes:buying' %}">Buying a Home</a></li>
						    <li><a href="{%url 'GreatHomes:mortgage' %}">Mortgages</a></li>
						    <li><a href="{%url 'GreatHomes:owningHome' %}">Owning A Home</a></li>
						  </ul>
					</li>
					<li>
						<a class="dropdown-toggle" data-toggle="dropdown">Selling
						  <span class="caret"></span></a>
						  <ul class="dropdown-menu">
						    <li><a href="{%url 'GreatHomes:selling' %}">Selling</a></li>
						    <li><a href="{%url 'GreatHomes:investing' %}">Investing</a></li>
						  </ul>
					<li><a href="{%url 'GreatHomes:aboutUs' %}">About Us</a></li>
					<li><a href="{%url 'GreatHomes:suscribeDisplay' %}">Newsfeed</a></li>
					<li><a href="{%url 'login:index' %}">Login</a></li>
				</ul>
			</div>
		</div>
	</div>

<div class = "main container">
	<div class = "col-xs-8 main2">
	<div class = "container">
	<div class = "row">
		<div class = "col-sm-4 col-xs-6">
			{% if user.url %}
			<img class = "userPicture" src="{{user.url}}" style= "width:90%">
			{% endif %}
			{% if user.url == null %}
			<img class = "userPicture" src="{% static 'GreatHomesRealty/avatar.png' %}" style = "width:90%">
			{% endif %}
			{% if user.id == request.session.login %}
	        <form id = "addPicture" class="addPicture" action="{%url 'UserDashboard:addUserImage' id=user.id %}" method="post" enctype="multipart/form-data">
	          {% csrf_token %}
	          {{UserImage.as_p}}
	          <input class = "btn btn-success" type="submit" value="Add Profile Picture">
	        </form>
	        {% endif %}
		</div>

		<div class = "col-sm-4 col-xs-4 userinfo">
			<h2>{{ user.firstName}} {{user.lastName }} </h2>
			<p><i class = "ion-ios-telephone"></i> {{user.phone}}</p>
			<p><i class = "ion-email"></i> {{user.email}}</p>
		</div>
	</div>
	</div>

	<div class = "row">
		<div class = "col-sm-12 col-xs-12 profileinfo">
			<p><span style="font-weight:bold">Agent Information: </span>{{user.profileInformation}}</p>
			{% if user.id == request.session.login %}
			<a class = "btn btn-success" href="{%url 'UserDashboard:editProfileDisplay' %}">Edit Description</a>
			{% endif %}
		</div>
	</div>
	</div>

	<div class = "col-xs-3 col-xs-offset-1 listings">
 		<h2>Listings</h2>
	{% for listing in listings %}
			<p><a href="{%url 'GreatHomes:showListing' id=listing.listing.id %}">{{listing.listing.addressStreet}} <br> {{listing.listing.addressCity}}, {{listing.listing.addressState}}. {{listing.listing.addressZipcode}}</a></p>
	{% endfor %}
	</div>
</div>

	<div class = "footer">
		<div class = "container-fluid">
		<div class = "row">
			<div class = "col-xs-3">
				<address>
				Principal Broker: Bill Yu<br>
				Cell: (410)-984-6661<br>
				Email: BillYu99@gmail.com <br>
				9822 Tenney Ct <br> Ellicott City, MD 21042
				</address>
			</div>
			<div class = "col-xs-8 col-xs-offset-1 footerlist">
				<ul>
					<li><a href="{%url 'GreatHomes:index' %}">Home</a></li>
					<li><a href="{%url 'GreatHomes:buying' %}">Buying</a></li>
					<li><a href="{%url 'GreatHomes:selling' %}">Selling</a></li>
					<li><a href="{%url 'GreatHomes:aboutUs' %}">About Us</a></li>
					<li><a href="{%url 'GreatHomes:suscribeDisplay' %}">Newsfeed</a></li>
				</ul>
			</div>
		</div>
		</div>
	</div>
</body>
</html>

apps/GreatHomesRealty/templates/GreatHomesRealty/displaySuscribers.html
<html>
<head>
	<title>Display Suscribers</title>
</head>
<body>
	<a href="{%url 'GreatHomes:suscribeDisplay' %}">Go Back To Newsfeed</a>
	<ul>
		{% for client in clients %}
		<li>{{client.firstName}} {{client.lastName}} {{client.email}}</li>
		{% endfor %}
	</ul>
</body>
</html>

apps/GreatHomesRealty/templates/GreatHomesRealty/viewAllListing.html
<html>
<head>
	<title></title>
	{% load staticfiles %}
	<meta name="viewport" content="width=device-width, initial-scale=0.5">
	<script src = "{% static '/js/jquery.js' %}" type="text/javascript"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'GreatHomesRealty/ionicons.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<style type="text/css">
</style>
<body>
	{% if request.session.login > 0 %}
	<header>
		<ul>
			<li><a href="{%url 'GreatHomes:index' %}">HomePage</a></li>
			<li><a href="{%url 'UserDashboard:index' %}">DashBoard</a></li>
			<li><a href="{%url 'UserDashboard:editProfileDisplay' %}">Edit Profile</a></li>
			<li><a href="{%url 'GreatHomes:showAgentListing' id=request.session.login %}">Your Profile</a></li>
			<li><a href="{%url 'GreatHomes:showAllListing' %}">Listings</a></li>
			<li><a href="{%url 'GreatHomes:addListingDisplay' %}">Add Listing</a></li>
		{% if user.user_level == "Admin" %}
			<li><a href="{%url 'UserDashboard:createDisplay' %}">Add New Agent</a></li>
		{% endif %}
			<li><a href="{%url 'UserDashboard:logout' %}">Log Off</a></li>
		</ul>
	</header>
	{% endif %}
	<div class = "header">
		<div class = "container-fluid">
			<div class = "col-sm-5">
				<h1><a href="{%url 'GreatHomes:index' %}"><i class = "ion-ios-home"></i> Great Homes Realty</a></h1>
			</div>
			<div class = "col-sm-7 navlinks">
				<ul>
					<li>
						  <a class="dropdown-toggle" data-toggle="dropdown">All Listings
						  <span class="caret"></span></a>
						  <ul class="dropdown-menu">
						    <li><a href="{%url 'GreatHomes:showAllListing' %}">For Sale</a></li>
						    <li><a href="{%url 'GreatHomes:showAllRentals' %}">For Rent</a></li>
						  </ul>
					</li>
					<li>
						  <a class="dropdown-toggle" data-toggle="dropdown">Buying
						  <span class="caret"></span></a>
						  <ul class="dropdown-menu">
						    <li><a href="{%url 'GreatHomes:buying' %}">Buying a Home</a></li>
						    <li><a href="{%url 'GreatHomes:mortgage' %}">Mortgages</a></li>
						    <li><a href="{%url 'GreatHomes:owningHome' %}">Owning A Home</a></li>
						  </ul>
					</li>
					<li>
						<a class="dropdown-toggle" data-toggle="dropdown">Selling
						  <span class="caret"></span></a>
						  <ul class="dropdown-menu">
						    <li><a href="{%url 'GreatHomes:selling' %}">Selling</a></li>
						    <li><a href="{%url 'GreatHomes:investing' %}">Investing</a></li>
						  </ul>
					<li>About Us</li>
					<li><a href="{%url 'GreatHomes:suscribeDisplay' %}">Newsfeed</a></li>
					<li><a href="{%url 'login:index' %}">Login</a></li>
				</ul>
			</div>
		</div>
	</div>

	<div class = "body">
		<div class = "container-fluid">
		{% for listing in allListings %}
			<div class = "col-md-4 col-sm-6 col-xs-6 picture">
				<div class = "row addressdiv">
					{% if listing.url %}
					<a class = "imagelist" href="{%url 'GreatHomes:showListing' id=listing.id %}"><img class = "listingimage" src="{{listing.url}}" height = "200" width = "300"></a>
					{% endif %}
					<address class = "address" style="width:90%"><a class = "imagelist" href="{%url 'GreatHomes:showListing' id=listing.id %}"><i class="ion-home icon-big"></i>
					{{listing.addressStreet}} <br>
					{{listing.addressCity}},
					{{listing.addressState}}. {{listing.addressZipcode}}
					<br>${{ listing.price }}</a> 
					</address>
				</div>
			</div>
		{% endfor %}
		</div>	
	</div>


	<div class = "footer">
		<div class = "container-fluid">
		<div class = "row">
			<div class = "col-xs-3">
				<address>
				Principal Broker: Bill Yu<br>
				Cell: (410)-984-6661<br>
				Email: BillYu99@gmail.com <br>
				9822 Tenney Ct <br> Ellicott City, MD 21042
				</address>
			</div>
			<div class = "col-xs-8 col-xs-offset-1 footerlist">
				<ul>
					<li><a href="{%url 'GreatHomes:index' %}">Home</a></li>
					<li><a href="{%url 'GreatHomes:buying' %}">Buying</a></li>
					<li><a href="{%url 'GreatHomes:selling' %}">Selling</a></li>
					<li><a href="{%url 'GreatHomes:aboutUs' %}">About Us</a></li>
					<li><a href="{%url 'GreatHomes:suscribeDisplay' %}">Newsfeed</a></li>
				</ul>
			</div>
		</div>
		</div>
	</div>
</body>
</html>