Great_Homes_Realty/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from apps.LoginAndReg.models import User as U

class UAdmin(admin.ModelAdmin):
    pass
admin.site.register(U, UAdmin)


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include('apps.LoginAndReg.urls', namespace = "login")),
    url(r'^UserDashboard/', include('apps.UserDashboard.urls', namespace = "UserDashboard")),
    url(r'^', include('apps.GreatHomesRealty.urls', namespace = "GreatHomes"))    # url(r'^s3direct/', include('s3direct.urls'))
]

apps/GreatHomesRealty/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static 
from django.conf import settings
from . import views
from views import Suscribe, Unsuscribe, SendMail, ClientLogin, AddListing, EditListing

urlpatterns = [
	url(r'^$', views.index, name = "index"),
	url(r'^addListingDisplay$', views.addListingDisplay, name = "addListingDisplay"),
	url(r'^addListing$', AddListing.as_view(), name = "addListing"),
	url(r'^addListingImage/(?P<id>\d+)$', views.addListingImage, name = "addListingImage"),
	url(r'^addMainImage/(?P<id>\d+)$', views.addMainImage, name = "addMainImage"),
	url(r'^editListingDisplay/(?P<id>\d+)$', views.editListingDisplay, name = "editListingDisplay"),
	url(r'^editListing/(?P<id>\d+)$', EditListing.as_view(), name = "editListing"),
	url(r'^showListing/(?P<id>\d+)$', views.showListing, name = "showListing"),
	url(r'^showAllListing$', views.showAllListing, name = "showAllListing"),
	url(r'^showAllRentals$', views.showAllRentals, name = "showAllRentals"),
	url(r'^showAgentListing/(?P<id>\d+)$', views.showAgentListing, name = "showAgentListing"),
	url(r'^addAgent/(?P<id>\d+)$', views.addAgent, name = "addAgent"),
	url(r'^deleteListing/(?P<id>\d+)$', views.deleteListing, name = "deleteListing"),
	url(r'^deleteImage/(?P<id>\d+)$', views.deleteImage, name = "deleteImage"),
	url(r'^deleteListingAgent/(?P<id>\d+)$', views.deleteListingAgent, name = "deleteListingAgent"),
	url(r'^sendMail/(?P<id>\d+)$', SendMail.as_view(), name = "sendMail"),
	url(r'^deleteMainImage/(?P<id>\d+)$', views.deleteMainImage, name = "deleteMainImage"),
	url(r'^suscribeDisplay$', views.suscribeDisplay, name = "suscribeDisplay"),
	url(r'^suscribe$', Suscribe.as_view(), name = "suscribe"),
	url(r'^unsuscribe$', Unsuscribe.as_view(), name = "unsuscribe"),
	url(r'^clientLogin$', ClientLogin.as_view(), name = "clientLogin"),
	url(r'^suscriptionEmail$', views.suscriptionEmail, name = "suscriptionEmail"),
	url(r'^displaySubscribers$', views.displaySubscribers, name = "displaySubscribers"),
	url(r'^contact$', views.contact, name = "contact"),
	url(r'^buying$', views.buying, name = "buying"),
	url(r'^selling$', views.selling, name = "selling"),
	url(r'^mortgage$', views.mortgage, name = "mortgage"),
	url(r'^investing$', views.investing, name = "investing"),
	url(r'^owningHome$', views.owningHome, name = "owningHome"),
	url(r'^aboutUs$', views.aboutUs, name = "aboutUs"),
	url(r'^latLon$', views.latLon, name = "latLon")

]

apps/LoginAndReg/urls.py
from django.conf.urls import url, include 
from . import views
from views import Register, Login, ResetPassword, ChangePassword

urlpatterns = [
	url(r'^$', views.index, name = "index"),
	url(r'^users$', Register.as_view(), name = "register"),
	url(r'^login$', Login.as_view(), name = "login"),
	url(r'^updateInfo/(?P<id>\d+)$', views.updateInfo, name = "updateInfo"),
	url(r'^updatePassword/(?P<id>\d+)$', views.updatePassword, name = "updatePassword"),
	url(r'^updateDescription$', views.updateDescription, name = "updateDescription"),
	url(r'^removeUser/(?P<id>\d+)$', views.removeUser, name = "removeUser"),
	url(r'^createUser$', views.createUser, name = "createUser"),
	url(r'^resetPasswordDisplay$', views.resetPasswordDisplay, name = "resetPasswordDisplay"),
	url(r'^resetPassword$', ResetPassword.as_view(), name = "resetPassword"),
	url(r'^changePassword$', ChangePassword.as_view(), name = "changePassword")
	]

apps/UserDashboard/urls.py
from django.conf.urls import url, include # Notice we added include
from . import views
from views import PostMessage

urlpatterns = [
	url(r'^$', views.index, name = "index"),
	url(r'^users/new$', views.createDisplay, name = "createDisplay"),
	url(r'^users/edit$', views.editProfileDisplay, name = "editProfileDisplay"),
	url(r'^logout$', views.logout, name = "logout"),
	url(r'^users/edit/(?P<id>\d+)$', views.adminEdit, name = "adminEdit"),
	url(r'^postMessage$', PostMessage.as_view(), name = "postMessage"),
	url(r'^deleteMessage/(?P<id>\d+)$', views.deleteMessage, name = "deleteMessage"),
	url(r'^addUserImage/(?P<id>\d+)$', views.addUserImage, name = "addUserImage")
]

apps/LoginAndReg/models.py
from __future__ import unicode_literals
from django.db import models
import re
from datetime import datetime
import bcrypt
import random

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')
PASSWORD_REGEX = re.compile(r'^(?=.*[A-Z])(?=.*\d)')
PHONE_REGEX = re.compile(r'^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}$')

class RegisterManager(models.Manager):
    def userRegister(self, firstName, lastName, email, password, confirmPassword, phone, session, changePassword, passcode):
		errors = {}

		try:
			user = User.registerMgr.get(email = email)
		except:
			user = 0
		if len(email) == 0:
		    errors['EmailRequired'] = ("Email is required")
		elif not EMAIL_REGEX.match(email):
		    errors['InvalidEmail'] = ("Invalid Email")
		if user != 0 and session == 0:
			errors['EmailDuplicate'] = "Email Already In Use!"
		if len(firstName) < 2 or len(lastName) < 2:
			errors['TwoCharacters'] = ("First name and last name must be at least two characters")
		if firstName.isalpha() == False or lastName.isalpha() == False:
			errors['IsAlpha'] = ("First and last name must contain only alphabetic characters")
		if len(password) < 1 or len(confirmPassword) < 1:
			errors['PasswordRequired'] = ("Password and confirm password is required")
		if len(password) < 8:
			errors['PasswordLength'] = ("Password needs to be at least 8 characters")
		if not PASSWORD_REGEX.match(password):
			errors['InvalidPassword'] = ("Password requires one uppercase letter and one number")
		if not PHONE_REGEX.match(phone):
			errors['InvalidPhone'] = ("Please enter a valid phone number")
		if password != confirmPassword:
			errors['PasswordNonmatch'] = ("Confirm password must match password")
		if passcode != "Ellicott042":
			errors['passcodeError'] = "Incorrect Passcode"
		if len(errors) is not 0:
			return (False, errors)
		elif len(errors) == 0 and session == 0:
			pw_bytes = password.encode('utf-8')
			hashed = bcrypt.hashpw(pw_bytes, bcrypt.gensalt())
			user = User.registerMgr.create(firstName = firstName, lastName = lastName, email=email, password = hashed, phone = phone)
			user.save()
			return (True, user)
		elif len(errors) == 0 and session > 0 and changePassword == False:
			User.registerMgr.filter(id = session).update(firstName = firstName, lastName = lastName, email = email, phone = phone, password = password)
			return (True, 1)
		elif len(errors) == 0 and  session > 0 and changePassword == True: 
			pw_bytes = password.encode('utf-8')
			hashed = bcrypt.hashpw(pw_bytes, bcrypt.gensalt())
			User.registerMgr.filter(id = session).update(password = hashed)
			return (True, 1)


class LoginManager(models.Manager):
	def login(self, email, password):
		errors = {}
		try:
			user = User.loginMgr.get(email = email)
		except:
			user = 0
		if user != 0:
			hashed = user.password.encode('utf-8')
			pw_bytes = password.encode('utf-8')
			if bcrypt.hashpw(pw_bytes, hashed) == hashed:
				a = 1
			else:
				errors["IncorrectLogin"] = "Incorrect Password"
		else:
			errors["NoEmail"] = "Entered Email Not in Database"
		print errors
		if len(errors) is not 0:
			return (False, errors)
		else:
			return (True, user)

class PasscodeManager(models.Manager):
	def resetPassword(self, passcode, password, confirmPassword):
		newPasscode = str(random.randint(1,10)) + str(random.randint(1,10)) + str(random.randint(1,10)) + str(random.randint(1,10))  + str(random.randint(1,10)) + str(random.randint(1,10)) 
		errors = {}
		if password != confirmPassword:
			errors['PasswordNonmatch'] = ("Confirm password must match password")
		if len(password) < 8:
			errors['PasswordLength'] = ("Password needs to be at least 8 characters")
		if not PASSWORD_REGEX.match(password):
			errors['InvalidPassword'] = ("Password requires one uppercase letter and one number")
		try:
			user = User.passcodeMgr.get(passcode = passcode)
		except:
			user = 0
		if user == 0:
			errors["IncorrectPasscode"] = "Incorrect Passcode"
		if user != 0 and len(errors) is 0:
			pw_bytes = password.encode('utf-8')
			hashed = bcrypt.hashpw(pw_bytes, bcrypt.gensalt())
			User.registerMgr.filter(passcode = passcode).update(password = hashed)
		if len(errors) is not 0:
			return (False, errors)
		else:
			return (True, user)

class User(models.Model):
	firstName = models.CharField(max_length=100)
	lastName = models.CharField(max_length=100)
	email = models.CharField(max_length=100)
	phone = models.CharField(null = True, max_length = 100)
	picture =  models.ImageField(null = True, upload_to = 'uploads/')
	url = models.CharField(max_length = 128,  null = True)
	user_level = models.CharField(max_length = 100, null = True)
	password = models.CharField(max_length=250)
	profileInformation = models.TextField(null = True)
	created_at = models.DateField(auto_now_add=True)
	updated_at = models.DateField(auto_now=True)
	registerMgr = RegisterManager()
	passcodeMgr = PasscodeManager()
	loginMgr = LoginManager()
	passcode = models.CharField(max_length= 50, null = True)

apps/LoginAndReg/views.py
from django.shortcuts import render, HttpResponse, redirect
from models import User
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.views.generic.edit import View
from django.http import JsonResponse
from django.core.mail import send_mail
import random
import json 
error_messages = {}

def index(request):
    return render(request, 'LoginAndReg/index.html')

class Register(View):
	def post(self, request):
		if request.method == "POST":
			global error_messages
			error_messages = {}
			result = User.registerMgr.userRegister(request.POST['first_name'], request.POST['last_name'], request.POST['email'].lower(), request.POST['password'], request.POST['confirm_password'], request.POST['phone'], 0, False, request.POST['passcode'])
			if result[0]:
				user = result[1]
				request.session['login'] = result[1].id
				if result[1].email == "billyu99@gmail.com" or result[1].email == "john123yu@gmail.com":
					user.user_level = "Admin"
					user.save()
				else:
					user.user_level = "Normal"
					user.save()
				return JsonResponse({"data": "true"})
			else:
				error_messages = result[1]
				return JsonResponse(error_messages)
		else:
			return JsonResponse({"error": "true"})

class Login(View):
	def post(self, request):
		if request.method == "POST":
			global error_messages
			error_messages = {}
			result = User.loginMgr.login(request.POST['email'].lower(), request.POST['password'])
			print request.POST['email'].lower()
			if result[0]:
				request.session['login'] = result[1].id
				return JsonResponse({"data": "true"})
			else:
				error_messages = result[1]
				return JsonResponse(error_messages)
		else:
			return JsonResponse({"error": "true"})

def resetPasswordDisplay(request):
	return render(request, 'LoginAndReg/resetPassword.html')

class ResetPassword(View):
	def post(self, request):
		if request.method == "POST":
			error_messages = {}
			user = User.loginMgr.filter(email = request.POST['email'].lower())
			if user:
				passcode = str(random.randint(1,10)) + str(random.randint(1,10)) + str(random.randint(1,10)) + str(random.randint(1,10))  + str(random.randint(1,10)) + str(random.randint(1,10))
				user[0].passcode = passcode
				print passcode
				user[0].save()
				fromEmail = "BillYu99@gmail.com"
				subject = "Great Homes Realty Password Reset"
				message =  "Someone requested a password reset for this email. Your passcode is " + str(passcode)
				emails = []
				emails.append(request.POST['email'])
				send_mail(
					subject,
					message,
					fromEmail,
					emails,
					fail_silently=False
				)
				error_messages['Success'] = "Check your email for a passcode and then fill out the form on the right. "
				error_messages['Success2'] = "Enter your passcode, then set your new password"
				return JsonResponse(error_messages)
			else:
				error_messages['NoEmail'] = "Entered email not in database"
				return JsonResponse(error_messages)
		else:
			return JsonResponse({"error": "true"})

class ChangePassword(View):
	def post(self, request):
		if request.method == "POST":
			error_messages = {}
			result = User.passcodeMgr.resetPassword(request.POST['passcode'], request.POST['password'], request.POST['confirmPassword'])
			if result[0]:
				request.session['login'] = result[1].id
				return JsonResponse({"data": "true"})
			else:
				error_messages = result[1]
				return JsonResponse(error_messages)
		else:
			return JsonResponse({"error": "true"})

def updateInfo(request, id):
	if request.method == "POST" and request.session['login'] > 0:
		error_messages = {}
		if(id > str(0)):
			user = User.registerMgr.get(id = id)
		else:
			user = User.registerMgr.get(id = request.session['login'])
		if id == str(0):
			result = User.registerMgr.userRegister(request.POST['first_name'], request.POST['last_name'], request.POST['email'].lower(), user.password, user.password, request.POST['phone'], request.session['login'], False, "Ellicott042")
		else:
			result = User.registerMgr.userRegister(request.POST['first_name'], request.POST['last_name'], request.POST['email'].lower(), user.password, user.password, request.POST['phone'], id, False, "Ellicott042")
		if result[0]:
			url = "/showAgentListing/" + str(user.id)
			return redirect(url)
		elif result[0] == False and id == str(0):
			error_messages = result[1]
			context = {
				'User': user,
				'error_messages': error_messages
			}
			print context['error_messages']
			return render(request, 'UserDashboard/editProfile.html',  context )
		elif result[0] == False and id > 0:
			error_messages = result[1]
			user = User.registerMgr.get(id = id)
			context = {
				'User': user,
				'error_messages': error_messages
			}
			print context['error_messages']
		return render(request, 'UserDashboard/adminEdit.html', context)
	else: 
		return redirect(reverse('login:index'))

def updatePassword(request, id):
	if request.method == "POST":
		error_messages = {}
		user = User.registerMgr.get(id = request.session['login'])
		if id == str(0):
			result = User.registerMgr.userRegister(user.firstName, user.lastName, user.email, request.POST['password'], request.POST['confirm_password'], user.phone, request.session['login'], True, "Ellicott042")
		else:
			result = User.registerMgr.userRegister(user.firstName, user.lastName, user.email, request.POST['password'], request.POST['confirm_password'], user.phone, id, True, "Ellicott042")
		if result[0]:
			url = "/showAgentListing/" + str(user.id)
			return redirect(url)
		elif result[0] == False and id == str(0):
			error_messages = result[1]
			return render(request, 'UserDashboard/editProfile.html',  error_messages )
		elif result[0] == False and id > 0:
			error_messages = result[1]
			user = User.registerMgr.get(id = id)
			context = {
				'User': user,
				'error_messages': error_messages
			}
			print context['error_messages']
		return render(request, 'UserDashboard/adminEdit.html', context)
	else: 
		return redirect(reverse('login:index'))

def updateDescription(request):
	if request.method == "POST":
		user = User.registerMgr.get(id = request.session['login'])
		user.profileInformation = request.POST['description']
		user.save()
		url = "/showAgentListing/" + str(user.id)
		return redirect(url)
	else: 
		return redirect(reverse('login:index'))

def removeUser(request, id):
	try:
		user = User.registerMgr.get(id = request.session['login'])
	except:
		user = 0
	if user.user_level == "Admin":
		User.registerMgr.get(id = id).delete()
		return redirect(reverse('UserDashboard:index'))
	else:
		return redirect(reverse('login:index'))

def createUser(request):
	error_messages = {}
	try:
		user = User.registerMgr.get(id = request.session['login'])
	except:
		user = 0
	if request.method == "POST" and user.user_level == "Admin":
		result = User.registerMgr.userRegister(request.POST['first_name'], request.POST['last_name'], request.POST['email'].lower(), request.POST['password'], request.POST['confirm_password'], request.POST['phone'], 0, False, "Ellicott042")
		if result[0]:
			user = result[1]
			user.user_level = "Normal"
			user.save()
			return redirect(reverse('UserDashboard:index'))
		else:
			error_messages = result[1]
			return render(request, 'UserDashboard/newUser.html',  error_messages )
	else:
		return redirect(reverse('login:index'))

apps/LoginAndReg/templates/LoginAndReg/changePasswordAjax.html
    <div class = "changePasswordAjax">
    {% if IncorrectPasscode %}
      <p class = 'error'> {{ IncorrectPasscode }} </p>
    {% endif %}
    <div class = "form-group">
      <label for = "passcode" class = "col-sm-3 control-label">Passcode:</label>
      <div class = "col-sm-9">
        <input type ='password' name ='passcode' id = "passcode" class = "form-control" placeholder = "Passcode">
      </div>
    </div>
    {% if PasswordLength %}
      <p class = 'error'> {{ PasswordLength }} </p>
    {% endif %}
    {% if InvalidPassword %}
      <p class = 'error'> {{ InvalidPassword }} </p>
    {% endif %}
    <div class = "form-group">
      <label for = "passcode" class = "col-sm-3 control-label">Password:</label>
      <div class = "col-sm-9">
        <input type ='password' name ='password' id = "password" class = "form-control" placeholder = "password">
      </div>
    </div>
    {% if PasswordNonmatch %}
      <p class = 'error'> {{ PasswordNonmatch }} </p>
    {% endif %}
    <div class = "form-group">
      <label for = "email" class = "col-sm-3 control-label">Confirm Password:</label>
      <div class = "col-sm-9">
        <input type ='password' name ='confirmPassword' id = "confirmPassword" class = "form-control" placeholder = "password">
        <input type='submit' value='Reset Password' class = "btn btn-success last-btn">
      </div>
    </div>
   </form>
  </div>
  </div>

apps/LoginAndReg/templates/LoginAndReg/resetPassword.html
<html>
    <head>
        <title>Login and Reg Index</title>
        {% load staticfiles %}
        <script src = "{% static '/js/jquery.js' %}" type="text/javascript"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'GreatHomesRealty/ionicons.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    </head>
    <style>
    {% load staticfiles %}
    .h1 {
      margin-left: 15%;
      margin-top: 3%;
    }
    .error {
      color:red;
      margin-left: 27%;
    }
    .green {
      color: green;
      margin-left: 27%;
    }
    .btn {
      margin-top: 15px;
    }
    .last-btn {
      margin-bottom: 10%;
    }
    body {
    background-image: linear-gradient(rgba(250, 197, 100, .65), rgba(250, 197, 100, .65)), url('{% static "GreatHomesRealty/diagonal_striped_brick.png" %}');
    }
    </style>
    <body>

{% if request.session.login > 0 %}
  <header>
    <ul>
      <li><a href="{%url 'GreatHomes:index' %}">HomePage</a></li>
      <li><a href="{%url 'UserDashboard:index' %}">DashBoard</a></li>
      <li><a href="{%url 'UserDashboard:editProfileDisplay' %}">Edit Profile</a></li>
      <li><a href="{%url 'GreatHomes:showAgentListing' id=request.session.login %}">Your Profile</a></li>
      <li><a href="{%url 'GreatHomes:showAllListing' %}">Listings</a></li>
      <li><a href="{%url 'GreatHomes:addListingDisplay' %}">Add Listing</a></li>
    {% if user.user_level == "Admin" %}
      <li><a href="{%url 'UserDashboard:createDisplay' %}">Add New Agent</a></li>
    {% endif %}
      <li><a href="{%url 'UserDashboard:logout' %}">Log Off</a></li>
    </ul>
  </header>
  {% endif %}
  <div class = "header">
    <div class = "container-fluid">
      <div class = "col-sm-5">
        <h1 class = "mainh1"><a href="{%url 'GreatHomes:index' %}"><i class = "ion-ios-home"></i> Great Homes Realty</a></h1>
      </div>
      <div class = "col-sm-7 navlinks">
        <ul>
          <li>
              <a class="dropdown-toggle" data-toggle="dropdown">All Listings
              <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{%url 'GreatHomes:showAllListing' %}">For Sale</a></li>
                <li><a href="{%url 'GreatHomes:showAllRentals' %}">For Rent</a></li>
              </ul>
          </li>
          <li>
              <a class="dropdown-toggle" data-toggle="dropdown">Buying
              <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{%url 'GreatHomes:buying' %}">Buying a Home</a></li>
                <li><a href="{%url 'GreatHomes:mortgage' %}">Mortgages</a></li>
                <li><a href="{%url 'GreatHomes:owningHome' %}">Owning A Home</a></li>
              </ul>
          </li>
          <li>
            <a class="dropdown-toggle" data-toggle="dropdown">Selling
              <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{%url 'GreatHomes:selling' %}">Selling</a></li>
                <li><a href="{%url 'GreatHomes:investing' %}">Investing</a></li>
              </ul>
          <li><a href="{%url 'GreatHomes:aboutUs' %}">About Us</a></li>
          <li><a href="{%url 'GreatHomes:suscribeDisplay' %}">Newsfeed</a></li>
          <li><a href="{%url 'login:index' %}">Login</a></li>
        </ul>
      </div>
    </div>
  </div>

  <h1 class = "h1">Enter Your Email</h1>
  <div class = "container-fluid">
    <div class  = "col-sm-6">
      <form action="{%url 'login:resetPassword' %}" method='post' class = "form-horizontal resetPasswordForm">
        {% csrf_token %}
          <div class = "resetPasswordAjax">
          <p class = 'error NoEmail'></p>
          <p class = 'green Success' ></p>
        <div class = "form-group">
        <label for = "email" class = "col-sm-3 control-label">Email:</label>
        <div class = "col-sm-9">
          <input type ='text' name ='email' id = "email" class = "form-control" placeholder = "Email">
          <input type='submit' value='Submit' class = "btn btn-success last-btn">
        </div>
        </div>
          </div>
      </form>
    </div>

  <div class = "col-sm-6">
  <p class = "green Success2"></p>
    <form action="{%url 'login:changePassword' %}" method='post' class = "form-horizontal changePasswordForm">
    {% csrf_token %}
      <div class = "changePasswordAjax">
      <p class = 'error IncorrectPasscode'></p>
    <div class = "form-group">
      <label for = "passcode" class = "col-sm-3 control-label">Passcode:</label>
      <div class = "col-sm-9">
        <input type ='password' name ='passcode' id = "passcode" class = "form-control" placeholder = "Passcode">
      </div>
    </div>
      <p class = 'error PasswordLength'></p>
      <p class = 'error InvalidPassword'></p>
    <div class = "form-group">
      <label for = "passcode" class = "col-sm-3 control-label">Password:</label>
      <div class = "col-sm-9">
        <input type ='password' name ='password' id = "password" class = "form-control" placeholder = "password">
      </div>
    </div>
      <p class = 'error PasswordNonmatch'></p>
    <div class = "form-group">
      <label for = "email" class = "col-sm-3 control-label">Confirm Password:</label>
      <div class = "col-sm-9">
        <input type ='password' name ='confirmPassword' id = "confirmPassword" class = "form-control" placeholder = "password">
        <input type='submit' value='Reset Password' class = "btn btn-success last-btn">
      </div>
    </div>
   </form>
  </div>
  </div>
    </body>
<script type="text/javascript">
  $('.resetPasswordForm').on('submit', function(e){
      e.preventDefault()
      $.ajax({
        url: 'resetPassword',
        method: 'post',
        data: $(this).serialize(),
        success: function(serverResponse){
          if(!serverResponse['NoEmail']) {
            $('.NoEmail').html("")
          } else {
            $('.NoEmail').html(serverResponse['NoEmail'])
          }
          if(!serverResponse['Success']) {
            $('.Success').html("")
          } else {
            $('.Success').html(serverResponse['Success'])
          }
          if(!serverResponse['Success2']) {
            $('.Success2').html("")
          } else {
            $('.Success2').html(serverResponse['Success2'])
          }
        }
      })
    });
  $('.changePasswordForm').on('submit', function(e){
      e.preventDefault()
      $.ajax({
        url: 'changePassword',
        method: 'post',
        data: $(this).serialize(),
        success: function(serverResponse){
          console.log(serverResponse)
          if(!serverResponse['IncorrectPasscode']) {
            $('.IncorrectPasscode').html("")
          } else {
            $('.IncorrectPasscode').html(serverResponse['IncorrectPasscode'])
          }
          if(!serverResponse['InvalidPassword']) {
            $('.InvalidPassword').html("")
          } else {
            $('.InvalidPassword').html(serverResponse['InvalidPassword'])
          }
          if(!serverResponse['PasswordLength']) {
            $('.PasswordLength').html("")
          } else {
            $('.PasswordLength').html(serverResponse['PasswordLength'])
          }
          if(serverResponse.data) { 
            window.location.replace("http://localhost:8000/UserDashboard/")
          }
        }
      })
    });
 </script>
</html>

apps/LoginAndReg/templates/LoginAndReg/resetPasswordAjax.html
 <div class = "resetPasswordAjax">
    {% if NoEmail %}
      <p class = 'error'> {{ NoEmail }} </p>
    {% endif %}
    {% if Success %}
      <p class = 'green'> {{ Success }} </p>
    {% endif %}
    <div class = "form-group">
    <label for = "email" class = "col-sm-3 control-label">Email:</label>
    <div class = "col-sm-9">
      <input type ='text' name ='email' id = "email" class = "form-control" placeholder = "Email">
      <input type='submit' value='Submit' class = "btn btn-success last-btn">
    </div>
    </div>
</div>